trigger:
  branches:
    include:
    - master
  paths:
    include:
    - terraform/*
    - src/*
    exclude:
    - terraform/README.md
    - src/README.md
    - src/LICENSE.md
jobs:
- job: terraform
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      buildType: specific
      project: 'e665c63d-1078-4c9e-a9d9-13bc1364e809'
      pipeline: 28
      specificBuildWithTriggering: true
      artifactName: dotnetapp
      downloadPath: '$(System.ArtifactsDirectory)'
  - task: CopyFiles@2
    displayName: 'Copy Files to: src/bin/Debug/netcoreapp2.1/publish'
    inputs:
      SourceFolder: '$(System.ArtifactsDirectory)/dotnetapp'
      TargetFolder: src/bin/Debug/netcoreapp2.1/publish
      CleanTargetFolder: true
      OverWrite: true
  - task: Terraform@2
    inputs:
      TemplatePath: 'terraform'
      Arguments: 'apply -target azurerm_app_service.main -auto-approve -var "sql_username=$(sqlUsername)" -var "sql_password=$(sqlPassword)"'
      InstallTerraform: true
      UseAzureSub: true
      ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
      ConnectedServiceNameARM: 'PlainServicePrincipal'
      ManageState: true
      SpecifyStorageAccount: true
      StorageAccountResourceGroup: '101-terraform-states'
      StorageAccountRM: '101terraformstates'
      StorageContainerName: 'dotnetdemo'
    displayName: 'Terraform run until webapp'
  - task: Terraform@2
    inputs:
      TemplatePath: 'terraform'
      Arguments: 'apply -auto-approve -var "sql_username=$(sqlUsername)" -var "sql_password=$(sqlPassword)"'
      InstallTerraform: true
      UseAzureSub: true
      ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
      ConnectedServiceNameARM: 'PlainServicePrincipal'
      ManageState: true
      SpecifyStorageAccount: true
      StorageAccountResourceGroup: '101-terraform-states'
      StorageAccountRM: '101terraformstates'
      StorageContainerName: 'dotnetdemo'
    displayName: 'Terraform run all'
