trigger:
  branches:
    include:
    - master
  paths:
    include:
    - pulumi/*
    exclude:
    - pulumi/README.md
jobs:
- job: pulumi
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      buildType: specific
      project: 'e665c63d-1078-4c9e-a9d9-13bc1364e809'
      pipeline: 28
      specificBuildWithTriggering: true
      artifactName: dotnetapp
      downloadPath: '$(System.ArtifactsDirectory)'
  - task: CopyFiles@2
    displayName: 'Copy Files to: src/bin/Debug/netcoreapp2.1/publish'
    inputs:
      SourceFolder: '$(System.ArtifactsDirectory)/dotnetapp'
      TargetFolder: src/bin/Debug/netcoreapp2.1/publish
      CleanTargetFolder: true
      OverWrite: true
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: 'pulumi'
    displayName: 'NPM install packages'
  - task: Pulumi@0
    inputs:
      azureSubscription: 'PlainServicePrincipal'
      command: 'config'
      args: 'set dotnet2019demo:sqlUsername $(sqlUsername)'
      cwd: 'pulumi'
      stack: 'dev'
    displayName: 'Set sql username'
  - task: Pulumi@0
    inputs:
      azureSubscription: 'PlainServicePrincipal'
      command: 'config'
      args: 'set --secret dotnet2019demo:sqlPassword $(sqlPassword)'
      cwd: 'pulumi'
      stack: 'dev'
    displayName: 'Set sql password'
  - task: Pulumi@0
    inputs:
      azureSubscription: 'PlainServicePrincipal'
      command: 'up'
      args: '--yes'
      cwd: 'pulumi'
      stack: 'dev'
    displayName: 'Exec infrastructure'
    name: pulumi
