trigger:
  branches:
    include:
    - master
  paths:
    include:
    - pulumi/*
    - src/*
    exclude:
    - pulumi/README.md
    - src/README.md
    - src/LICENSE.md
jobs:
- job: pulumi
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      projects: 'src'
      zipAfterPublish: false
      modifyOutputPath: false
    displayName: 'Build and publish ASP.NET Core app'
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: 'pulumi'
    displayName: 'NPM install packages'
  - task: Pulumi@0
    inputs:
      azureSubscription: 'PlainServicePrincipal'
      command: 'up'
      args: '--yes'
      cwd: 'pulumi'
      stack: 'dev'
    displayName: 'Exec infrastructure'
    name: pulumi
