trigger:
  branches:
    include:
    - master
  paths:
    include:
    - arm/*
    exclude:
    - arm/README.md
jobs:
- job: arm
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      buildType: specific
      project: 'e665c63d-1078-4c9e-a9d9-13bc1364e809'
      pipeline: 28
      specificBuildWithTriggering: true
      artifactName: dotnetapp
      downloadPath: '$(System.ArtifactsDirectory)'
  - task: CopyFiles@2
    displayName: 'Copy Files to: src/bin/Debug/netcoreapp2.1/publish'
    inputs:
      SourceFolder: '$(System.ArtifactsDirectory)/dotnetapp'
      TargetFolder: src/bin/Debug/netcoreapp2.1/publish
      CleanTargetFolder: true
      OverWrite: true
  - task: AzureResourceGroupDeployment@2
    displayName: 'Azure Deployment'
    inputs:
      azureSubscription: PlainServicePrincipal
      resourceGroupName: 'armdn2019-rg'
      location: 'West Europe'
      csmFile: arm/azuredeploy.json
      overrideParameters: '-sqlUsername $(sqlUsername) -sqlPassword $(sqlPassword)'
      deploymentMode: Complete
  - task: AzureRmWebAppDeployment@4
    displayName: 'Azure App Service Deploy'
    inputs:
      azureSubscription: PlainServicePrincipal
      WebAppName: 'armdn2019-as'
      packageForLinux: '$(System.DefaultWorkingDirectory)/src/bin/Debug/netcoreapp2.1/publish'
