trigger:
  branches:
    include:
    - master
  paths:
    include:
    - ansible/*
    - src/*
    exclude:
    - ansible/README.md
    - src/README.md
    - src/LICENSE.md
jobs:
- job: ansible
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      projects: 'src'
      zipAfterPublish: false
      modifyOutputPath: false
    displayName: 'Build and publish ASP.NET Core app'
  - script: |
      pip install 'ansible[azure]' --user
    displayName: 'Install dependencies'
  - task: AzureCLI@1
    displayName: 'Azure Login'
    inputs:
      azureSubscription: PlainServicePrincipal
      scriptLocation: inlineScript
      inlineScript: |
       az login --service-principal --username $(AZURE_CLIENT_ID) --password $(AZURE_SECRET) --tenant $(AZURE_TENANT)
       az account set --subscription $(AZURE_SUBSCRIPTION_ID)
  - task: ms-vscs-rm.vss-services-ansible.ansible-task.Ansible@0
    displayName: 'Run playbook'
    inputs:
      playbookPathOnAgentMachine: ansible/app.yml
